declare module "*.module.css";
declare module "*.module.scss";
declare module "*.module.sass";
declare module "*.css";
declare module "*.scss";
declare module "*.sass";
declare module '*.jpg';
declare module '*.png';
declare module '*.ico';